- name: Get mongodb root Default Password
  shell: cat /credentials/password.txt | awk 'NR==2' |awk -F ":" '{print $2}'
  register: mongodb_password 

- name: Create databases
  mongodb_user:
    login_user: root
    login_password: '{{mongodb_password.stdout}}'
    database: parse
    name: parse
    state: present
    password: websoft9
    roles: readWrite

- name: Install Parse Server and Parse Dashboard
  shell: sudo npm install -g parse-server parse-dashboard

- name: mkdir parse-server
  file:
    path: /etc/parse-server
    state: directory

    
- name: mkdir parse-server Log
  file:
    path: /var/log/parse-server
    state: directory

- name: Configuration Parse Server
  template:
    src: parse-server.json.jinja2
    dest: /etc/parse-server/parse-server.json

- name: Configuration Parse Server systemctl
  copy:
    src: parse-server.service
    dest: /lib/systemd/system/

- name: Start Parse Server
  service:
    name: parse-server.service
    state: restarted
    enabled: yes

- name: Configuration Parse Dashboard
  template:
    src: parse-dashboard.json.jinja2
    dest: /etc/parse-server/parse-dashboard.json

- name: Configuration Parse Dashboard systemctl
  copy:
    src: parse-dashboard.service
    dest: /lib/systemd/system/

- name: Start Parse Dashboard
  service:
    name: parse-dashboard.service
    state: restarted
    enabled: yes

- name: set reverse porxy
  copy: 
    src: default
    dest: /etc/nginx/conf.d/default.conf

- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: Write Databases Password
  template:
    src: password.txt.jinja2
    dest: /credentials/password.txt
    mode: 644

- name: Write rc.local
  shell: echo "#!/bin/bash" > /etc/rc.local

- name: restart rc.local
  service: name=rc.local state=restarted enabled=yes


- name: Databases Random Password
  template: 
    src: init.sh.jinja2
    dest: /root/init.sh
    mode: 0750

- name: Setting Startup
  lineinfile:
    path: /etc/rc.local
    regexp: '/root/init.sh'
    line: '/root/init.sh'
    mode: 0750